pipeline {
  agent none
  options {
    disableResume()
  }
  stages {
    stage('Build') {
      agent { label 'build' }
      steps {
        script {
          openshift.withCluster() {
            def filesInThisCommitAsString = sh(script:"git diff --name-only HEAD~1..HEAD | grep '^' || echo -n ''", returnStatus: false, returnStdout: true).trim()
            def hasChangesInPath = (filesInThisCommitAsString.length() > 0)
            echo "Files Changed ..."
            echo "${filesInThisCommitAsString}"
            if (!currentBuild.rawBuild.getCauses()[0].toString().contains('UserIdCause') && !hasChangesInPath){
              currentBuild.rawBuild.delete()
              error("No changes detected in the path ('^')")
            }

            // Fire up the angular builder
            echo "Running bcmi-angular builder"
            def angularSelector = openshift.selector("bc", "bcmi-angular").startBuild()
            angularSelector.untilEach(1) {
              return it.object().status.phase == "Complete"
            }
            echo "Deploying to BCMI"
            def nrcedSelector = openshift.selector("bc", "bcmi-build").startBuild()
            nrcedSelector.untilEach(1) {
              return it.object().status.phase == "Complete"
            }
            
            echo "BCMI complete and deployed to Dev"            
          }
        }
      }
    }
  }
}
